version: '3.4'

services:
  copagames.api:
    image: ${DOCKER_REGISTRY-}copagamesapi
    build:
      context: .
      dockerfile: Dockerfile
  copagames.front:
    image: ${DOCKER_REGISTRY-}copagamesfront
    build:
      context: ./copa-front
      dockerfile: Dockerfile
